spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/permission?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: false


  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: com.kuang.model
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.taoan.data.dao: debug